### PR TITLE
Adjust animations to look more natural and fix small issues

### PR DESCRIPTION
**Pull request by alexfrederiksen**
Adjusts animations to be with respect to the window center for position
interpolation, which makes things less strange looking when window
scaling takes longer than translating. Also clamps animation size to
window size to resolve blurring artifacts behind the window. Also make
animation fly in from a random direction off screen (:

### CODE REVIEW

**Comment by dccsillag** [comment]
Thank you for the contributions!! Really nice work.

BTW, Have you experimented with other open-window animations as well (besides fly in from some point outside the screen)? I think that later on we should add a config option on that, supporting a couple of options (definetly including fly-in, it's a really cool effect).

**Comment by dccsillag** [comment]
Quick update -- if we are doing open-window animations then we *really* need something like `open_window_animations_exclude` or `animations_exclude`. This fly-in window open animation is really messing up my XMonad GridSelect (to be clear, not because of artefacts, but because fly-in isn't a good match for this window).

**Comment by alexfrederiksen** [comment]
Glad you like it! Yea, adding a config option for this would probably be a good idea xD. I've also experimented with windows spawning from the center, which looks pretty alright as well, I could add that as an option too perhaps. I'll try to work on this throughout the week (:

**Comment by dccsillag** [comment]
Oh, great, thanks!

So I think I'm going to wait for some config option on that before merging, to avoid surprises for anyone who is currently using this fork (imagine if suddenly your windows started flying in from nowhere!).

**Comment by dccsillag** [comment]
Actually, do you mind if I implement that choice for animation method? I've got some spare time now, and would love to get your work merged (especially the misc fixes and animate by center! I think that'll solve some stuff I've been noticing).

**Comment by alexfrederiksen** [comment]
Sure, feel free to! Apologies I haven't gotten around to doing it yet.

**Comment by dccsillag** [comment]
No worries. OK, so I'll get working on this.

**Comment by dccsillag** [comment]
It appears that you have to grant me permission to push onto your fork/branch (which makes sense, I suppose): https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork.

EDIT: It's that "allow edits from maintainers" checkbox.

**Comment by alexfrederiksen** [comment]
Hmm. It seems to be checked: "Allow edits and access to secrets by maintainers"

**Comment by dccsillag** [comment]
When I try to do a `git push` (or similar), I get

```
remote: Permission to alexfrederiksen/picom.git denied to dccsillag.
```

And then one more line. If I have a HTTPS remote, the second line is

```
fatal: unable to access 'https://github.com/alexfrederiksen/picom.git/': The requested URL returned error: 403
```

If it's a SSH remote, the second line (well, +3rd and 4th) is

```
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
and the repository exists.
```

Thing is, here on github it tells me (right above the merge button area): "Add more commits by pushing to the implement-window-animations branch on alexfrederiksen/picom."
So I guess the problem is probably on my end here. I'll keep trying things out here, I guess.

**Comment by dccsillag** [comment]
I just tried a whole bunch of methods for pushing to a PR, all of them with the same results.

Github's help clearly states on https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork:

> You can only make commits on pull request branches that:
>
> - are opened in a repository that you have push access to and that were created from a fork of that repository
> - are on a user-owned fork
> - have permission granted from the pull request creator
> - don't have branch restrictions that will prevent you from committing

I _think_ all of these are fulfilled, but could you give it a look? Thanks.

**Comment by dccsillag** [comment]
I think I give up trying to push the commits. Instead, I'm attaching the output of a `git format-patch`. Could you please apply it? That can be done by running

```
git am dccsillag-commits-pr8.txt
```

(I had to use a `.txt` extension so that I could attach it here; ideally it would have a `.patch` extension.)

[dccsillag-commits-pr8.txt](https://github.com/dccsillag/picom/files/6903813/dccsillag-commits-pr8.txt)

**Comment by alexfrederiksen** [comment]
Sure (:. I have no idea what's going on in git here. It was actually a bit awkward making this pull request since it was a fork of fork, and I ended up forking actual picom, then tracking your remote branch. I can apply that patch in an hour when I get off work (;

**Comment by dccsillag** [comment]
> It was actually a bit awkward making this pull request since it was a fork of fork, and I ended up forking actual picom, then tracking your remote branch.

Huh, I wonder if that's got anything to do with these issues. Something to look into later.

> I can apply that patch in an hour when I get off work (;

Great! Thank you very much!!

**Comment by alexfrederiksen** [comment]
Done

**Comment by dccsillag** [comment]
Thank you so much!! I'll get working on merging this now.

**Comment by dccsillag** [comment]
Done! :tada: :tada: :tada:

**Comment by alexfrederiksen** [comment]
Yeet ((((:

**Pull request merged**
